##这些是传入模型的参数
dataset: mvtec
classes_name: ['carpet', 'grid', 'leather', 'tile', 'wood',
                   'bottle', 'cable', 'capsule', 'hazelnut', 'metal_nut', 'pill',
                   'screw', 'toothbrush', 'transistor', 'zipper'] # 实验所需要的类别
#classes_name: ['cable','capsule','carpet','hazelnut','metal_nut','pill','tile','wood','zipper'] # 实验所需要的类别
img_resize: 336
img_cropsize: 336
resolution: 400
batch_size: 16
visualize: True
output_dir: ./output
load_memory: True
cal_pro: False
experiment_indx: 0
gpu_id: 0
pure_test: False
k_shot: 0
r_list: [3,5]
features_list: [23]
backbone: ViT-L-14-336
pretrained_dataset: openai
use_cpu: 0
#checkpoint_dirs: {'anomaly':"./zcr/BLIP/ab_mvtec8",'normal':"./zcr/BLIP/nor_mvtec8"}
#checkpoint_dirs: "./zcr/BLIP/mvtec8"
